CREATE DATABASE ds;
USE ds;
CREATE TABLE log(
	id INT NOT NULL AUTO_INCREMENT,
	event_type INT NOT NULL,
	app_name VARCHAR(255) NOT NULL,
	other DATE,
	PRIMARY KEY ( id ));
CREATE TABLE dictionary(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	day INT NOT NULL,
	start_time INT NOT NULL,
	end_time INT NOT NUll,
	participants VARCHAR(255) NOT NULL,
	PRIMARY KEY ( id ));
CREATE TABLE time(
	id INT NOT NULL AUTO_INCREMENT,
	node_id INT NOT NULL UNIQUE,
	node1 INT NOT NULL,
	node2 INT NOT NULL,
	node3 INT NOT NULL,
	node4 INT NOT NULL,
	PRIMARY KEY ( id ));
